<h1>Te encuentras en la vista fotos</h1>

<h3><?php echo $this -> interactua_php ?></h3>

<label>Selecciona una vista ...</label>
<ul>
    <li><a href="http://ozoutletzf2.localhost/">vista index</a>
        <li><a href="http://ozoutletzf2.localhost/fotos">vista fotos</a>
            <li><a href="http://ozoutletzf2.localhost/musica">vista musica</a>
</ul>

<h3>El valor del par&aacute;metro id es = <?php echo $this->id ?></h3>

<?php echo $this->count_imagenes ?>

<?php echo $this->imagenes ?>